# If you are having connection issues it is recommended to set it
# to PLUS_8 because the power consumption difference is negligible.
CONFIG_ZMK_BLE=y

# There are no LED's and OLED's so turn off external power
CONFIG_ZMK_EXT_POWER=n

# Enable sleep for halves
CONFIG_ZMK_SLEEP=y

# Sleep timeout: 15 min
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000

# Enable Bluetooth battery reporting service
CONFIG_BT_BAS=y

# Enable ZMK battery reporting
CONFIG_ZMK_BATTERY_REPORTING=y

# Enable central reporting of split battery levels to hosts
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y

# mouse
# CONFIG_ZMK_MOUSE=y
CONFIG_ZMK_POINTING=y
CONFIG_ZMK_POINTING_SMOOTH_SCROLLING=n
